### ISSUE TITLE
Segmentation fault when playing a note

### ISSUE THREAD

**Issue by ycollet** [FigBug/Piano#1]
I am building  Piano on Fedora 36 and I am not able to use it.
When I play a key on Piano, I've got a segmentation fault:

```
Thread 6 "JUCE ALSA" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff514c640 (LWP 15297)]
ms4 (N=<optimized out>, z=<optimized out>, y=0x5555562a905c, x=<optimized out>) at ../../Source/utils.cpp:100
100             v = simde_mm_sub_ps (simde_mm_shuffle_ps (w, w, SIMDE_MM_SHUFFLE(0, 1, 2, 3)), *x4);
(gdb) where
#0  ms4 (N=<optimized out>, z=<optimized out>, y=0x5555562a905c, x=<optimized out>) at ../../Source/utils.cpp:100
#1  dwgs::tran2long4 (delay=8, this=0x55555629e1e0) at ../../Source/dwgs.cpp:101
#2  dwgs::tran2long4 (delay=8, this=0x55555629e1e0) at ../../Source/dwgs.cpp:32
#3  PianoNote::go4 (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:296
#4  0x00005555557a370d in PianoNote::goDownDelayed (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:148
#5  0x00005555557a42e1 in PianoNote::goDown (this=<optimized out>) at ../../Source/qiano.cpp:138
#6  PianoNote::goUpDelayed (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:113
#7  0x00005555557a46d8 in PianoNote::goUp (this=<optimized out>) at ../../Source/qiano.cpp:99
#8  Piano::process (this=this@entry=0x55555591d720, out=<optimized out>, samples=samples@entry=512) at ../../Source/qiano.cpp:689
#9  0x00005555557a81d2 in Piano::process (offset=<optimized out>, samples=<optimized out>, out=0x7ffff514b980, this=0x55555591d720) at ../../Source/qiano.cpp:708
#10 Piano::process (this=<optimized out>, outS=<optimized out>, sampleFrames=<optimized out>, midi=...) at ../../Source/qiano.cpp:765
#11 0x00005555555d16e1 in PianoAudioProcessor::processBlock (this=0x55555591d3c0, buffer=..., midi=...)
    at ../../../modules/juce/modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.h:242
#12 0x00005555556467c5 in juce::AudioProcessorPlayer::audioDeviceIOCallbackWithContext (this=<optimized out>, inputChannelData=<optimized out>, 
    numInputChannels=<optimized out>, outputChannelData=<optimized out>, numOutputChannels=<optimized out>, numSamples=<optimized out>, context=...)
    at ../../../modules/juce/modules/juce_audio_utils/players/juce_AudioProcessorPlayer.cpp:328
#13 0x00005555555c1c15 in juce::StandalonePluginHolder::CallbackMaxSizeEnforcer::audioDeviceIOCallbackWithContext (this=0x55555591d370, inputChannelData=0x0, 
    numInputChannels=<optimized out>, outputChannelData=0x5555559f8f70, numOutputChannels=<optimized out>, numSamples=512, context=...)
    at ../../../modules/juce/modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h:469
#14 0x0000555555624d5c in juce::AudioDeviceManager::audioDeviceIOCallbackInt (context=..., numSamples=512, numOutputChannels=2, outputChannelData=0x5555559f8f70, 
    numInputChannels=0, inputChannelData=0x0, this=0x55555591cb70) at ../../../modules/juce/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:1002
#15 juce::AudioDeviceManager::CallbackHandler::audioDeviceIOCallbackWithContext (this=<optimized out>, ins=0x0, numIns=0, outs=0x5555559f8f70, numOuts=2, 
    numSamples=512, context=...) at ../../../modules/juce/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:79
#16 0x000055555561f705 in juce::(anonymous namespace)::ALSAThread::run (this=0x555555a02560) at ../../../modules/juce/modules/juce_core/memory/juce_HeapBlock.h:182
#17 0x000055555566eb5c in juce::Thread::createNativeThread(juce::Thread::Priority)::{lambda(void*)#1}::_FUN(void*) [clone .lto_priv.0] ()
    at ../../../modules/juce/modules/juce_core/threads/juce_Thread.cpp:98
#18 0x00007ffff768cdcd in start_thread (arg=<optimized out>) at pthread_create.c:442
#19 0x00007ffff7712630 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by getdunne** [comment]
I get a similar failure when testing the latest VST build on Windows:

Exception thrown at 0x00007FFF1BA68F00 (Piano.dll) in Unify.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by michelemaroni** [comment]
Potentially related, both the VST and VST3 plugins crashes whenever I try to play a note on windows. No error message appears.
The organ works nicely instead.

> I get a similar failure when testing the latest VST build on Windows:
> 
> Exception thrown at 0x00007FFF1BA68F00 (Piano.dll) in Unify.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by AASomarakis** [comment]
Crashes the DAW.
When Left Click on the Plugin Piano UI, same with MIDI Input. Can't test input from rotary / fader mappings.

Windows 11 x64 
Reaper v.6.73
16 bit / 48 kHz
16 bit / 44.1 kHz

i7700 4.2GHz
16 GB Ram

**Comment by tomlikesmangos** [comment]
Same here, I downloaded it from the SocaLabs website and it crashes my DAW when I try to play a note. I'm not 100% sure I'm commenting this in the exact right place as I'm a layman and GitHub is scawy, but I'm posting anyway 😔 

Windows 11 x64
Reaper v.6.81
Steinberg UR44 @ 44.1kHz

Intel Core i5 10210U @ 1.60GHz
8 GB RAM

PS: the organ works perfectly and sounds amazing, thanks SocaLabs and the individuals behind all of these plugins for doing your mysterious computer wizardry all so that I can download your funny keyboard instruments and make sounds with them without having to leave my house

**Comment by SilverLPs** [comment]
Same problem, VST and VST3 crashes in Bitwig on Kubuntu 24.04 Linux with Segfault and no further error message.
Opens without any problems but as soon as I play a note: segfault crash.

**Comment by LoveBodhi** [comment]
This plugin is not usable because program crashes when attempt to play note!

**Comment by garrettendi** [comment]
I'm having the same issue on Linux, a crash when I play a note. If the above PR fixes the issue, then could we maybe get a new release? I tried building the PR myself but I think I'm missing certain libraries.

**Comment by FigBug** [comment]
sorry for delay getting to this, new release should be out today

**Comment by garrettendi** [comment]
That's great! Thanks you so much! Where will we find the new release please?

**Comment by FigBug** [comment]
> That's great! Thanks you so much! Where will we find the new release please?

https://socalabs.com/synths/piano/

**Comment by garrettendi** [comment]
> > That's great! Thanks you so much! Where will we find the new release please?
> 
> https://socalabs.com/synths/piano/

Thank you! For some reason I wasn't seeing the updated page. I'll try and test it out ASAP. I've been looking forward to this!

**Comment by garrettendi** [comment]
Can we reopen this please? I am still getting the same bug. The first note I press plays then it crashes on the second and I have to force quit. Reaper on elementary OS 8. I am using the VST3 plugin.

EDIT: I've tried the LV2 and VST as well. Same crash, sometimes on the first note. VST3 has the issue regardless of running as a seperate/dedicated/native process. I can't find the logs at the moment. I've cleared the cache and re-scanned, even restarted my laptop and the same bug persists. It crashes either on the first or second note.

**Comment by FigBug** [comment]
Crash is gone on macOS. Still trying to track it down on Windows.

**Comment by garrettendi** [comment]
Thanks, have you been able to work out the bug in Linux or is that coming? I can test the fix on the next Linux release.

**Comment by LoveBodhi** [comment]
![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
Still not fixed on Windows...

**Comment by a5632645** [comment]
> ![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
> Still not fixed on Windows...

maybe you can try my fork version.at least it works great on my computer using vscode standalone or vst3 in live and renoise.  
https://github.com/a5632645/Piano  
please choosing the fix-more branch, I haven't test the fix branch after last merge.

**Comment by FigBug** [comment]
> > ![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
> >       
> >         [
> >           
> >         
> >             ![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
> >           ](https://private-user-images.githubusercontent.com/37089530/495932871-0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxMTIyMjQsIm5iZiI6MTc2MDExMTkyNCwicGF0aCI6Ii8zNzA4OTUzMC80OTU5MzI4NzEtMDI5N2EwYjEtM2I5Ni00OTEyLWFjOGMtZmRhNmQ2YzRlMWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTQ1OTEwN2IzMjJlYzEwNmY1NzBmZjc4ZDdlOTYzYjk1ODFlNThiMjcyOGUwNzJiNTUwMGRiOGRkNTdiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v0FwE3JeaLVvLIYnpZLJP8rqWVpQt9irOuNLpc9t7oU)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/37089530/495932871-0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxMTIyMjQsIm5iZiI6MTc2MDExMTkyNCwicGF0aCI6Ii8zNzA4OTUzMC80OTU5MzI4NzEtMDI5N2EwYjEtM2I5Ni00OTEyLWFjOGMtZmRhNmQ2YzRlMWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTQ1OTEwN2IzMjJlYzEwNmY1NzBmZjc4ZDdlOTYzYjk1ODFlNThiMjcyOGUwNzJiNTUwMGRiOGRkNTdiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v0FwE3JeaLVvLIYnpZLJP8rqWVpQt9irOuNLpc9t7oU)
> >         
> >       
> > Still not fixed on Windows...
> 
> maybe you can try my fork version.at least it works great on my computer using vscode standalone or vst3 in live and renoise. https://github.com/a5632645/Piano please choosing the fix-more branch, I haven't test the fix branch after last merge.

can you open another pull request?

**Comment by a5632645** [comment]
> > > ![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
> > >       
> > >         [
> > >           
> > >         
> > >             ![Image](https://github.com/user-attachments/assets/0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac)
> > >           ](https://private-user-images.githubusercontent.com/37089530/495932871-0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxMTIyMjQsIm5iZiI6MTc2MDExMTkyNCwicGF0aCI6Ii8zNzA4OTUzMC80OTU5MzI4NzEtMDI5N2EwYjEtM2I5Ni00OTEyLWFjOGMtZmRhNmQ2YzRlMWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTQ1OTEwN2IzMjJlYzEwNmY1NzBmZjc4ZDdlOTYzYjk1ODFlNThiMjcyOGUwNzJiNTUwMGRiOGRkNTdiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v0FwE3JeaLVvLIYnpZLJP8rqWVpQt9irOuNLpc9t7oU)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://private-user-images.githubusercontent.com/37089530/495932871-0297a0b1-3b96-4912-ac8c-fda6d6c4e1ac.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxMTIyMjQsIm5iZiI6MTc2MDExMTkyNCwicGF0aCI6Ii8zNzA4OTUzMC80OTU5MzI4NzEtMDI5N2EwYjEtM2I5Ni00OTEyLWFjOGMtZmRhNmQ2YzRlMWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTQ1OTEwN2IzMjJlYzEwNmY1NzBmZjc4ZDdlOTYzYjk1ODFlNThiMjcyOGUwNzJiNTUwMGRiOGRkNTdiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v0FwE3JeaLVvLIYnpZLJP8rqWVpQt9irOuNLpc9t7oU)
> > >         
> > >       
> > > Still not fixed on Windows...
> > 
> > maybe you can try my fork version.at least it works great on my computer using vscode standalone or vst3 in live and renoise. https://github.com/a5632645/Piano please choosing the fix-more branch, I haven't test the fix branch after last merge.
> 
> can you open another pull request?

i haven't test that branch on other platforms(Linux and macos) and other DAWs. it may not work perfectly on other computers too. maybe you should test that branch first?
and I have changed too many codes, if you can accept that then I can make a pull request.

**Comment by FigBug** [comment]
> i haven't test that branch on other platforms(Linux and macos) and other DAWs. it may not work perfectly on other computers too. maybe you should test that branch first? and I have changed too many codes, if you can accept that then I can make a pull request.

Just tested on macOS and it's working fine (but then again, it was always working on macOS)

**Comment by tomlikesmangos** [comment]
still crashes on windows. using Reaper. tried the VSTi and the VST3i versions. Downloaded from this link. https://socalabs.com/synths/piano/ file version says 1.0.1

**Comment by a5632645** [comment]
> > i haven't test that branch on other platforms(Linux and macos) and other DAWs. it may not work perfectly on other computers too. maybe you should test that branch first? and I have changed too many codes, if you can accept that then I can make a pull request.
> 
> Just tested on macOS and it's working fine (but then again, it was always working on macOS)

hey, i just test that fix-more branch on my WSL2 ubuntu-18 using reaper DAW, and it works fine. No segement fault, but it happends that some discontinue at lower notes(high note are great), i dont know that is code issue or just cpu issue(Release build generate a 33MB .so file, it's abnormal), maybe someone should test it on native Linux. Would you like me to create a pull request?

<img width="1344" height="426" alt="Image" src="https://github.com/user-attachments/assets/c5d13973-88e8-4fbd-9d30-e1ab9faac4cd" />

EDIT: this might be the cpu issue, i am using offline render and no segement fault happen.

<img width="937" height="555" alt="Image" src="https://github.com/user-attachments/assets/183410e1-599b-4bbc-bdd0-0822fd52befa" />

you can hear this audio here, sound great.
https://1drv.ms/u/c/3a3f344e006a4200/EWUXzp0UWkNCh1hBaJgmZTsBqUO7oYqwZlL9SEd4aE_8Og?e=ji7Pgc

**Comment by FigBug** [comment]
> Would you like me to create a pull request?

Yes, please

**Comment by FigBug** [comment]
I've merged, but something sounds wrong. I will investigate more later. Sounds quite harsh now.

**Comment by a5632645** [comment]
> I've merged, but something sounds wrong. I will investigate more later. Sounds quite harsh now.

if you remove the
```
	gin::AudioMidiFifo 		fifoIn {2, interalBlockSize};
	gin::AudioMidiFifo		fifoOut {2, interalBlockSize};
	juce::AudioSampleBuffer workBuffer {2, interalBlockSize};
```
and directly write samples into juce buffer
```
    std::span<float> leftBlock{ buffer.getWritePointer(0), static_cast<size_t>(buffer.getNumSamples()) };
    std::span<float> rightBlock{ buffer.getWritePointer(1), static_cast<size_t>(buffer.getNumSamples()) };
    piano.process (leftBlock, midi);
```
that works.

**Comment by LoveBodhi** [comment]
Windows build was cancelled due to some reason!
https://github.com/FigBug/Piano/actions/runs/18435242869/job/52527825890

**Comment by LoveBodhi** [comment]
Program Crash may be **invalid pointer**.

**Comment by garrettendi** [comment]
Any update on this please? No worries if not it's a busy time of year!

**Comment by FigBug** [comment]
> Any update on this please? No worries if not it's a busy time of year!

can you try this version? https://github.com/FigBug/Piano/releases/tag/v1.0.2

**Comment by garrettendi** [comment]
> > Any update on this please? No worries if not it's a busy time of year!
> 
> can you try this version? https://github.com/FigBug/Piano/releases/tag/v1.0.2

That is better, in that it no longer crashes. But the first note distorts badly and subsequent notes don't play at all.

I'm using stock laptop sound card, ALSA drivers, and I've tried several combinations of priority and buffer sizes.

CPU is Pentium Silver N5030 with 8GB RAM.

**Comment by FigBug** [comment]
> > > Any update on this please? No worries if not it's a busy time of year!
> > 
> > 
> > can you try this version? https://github.com/FigBug/Piano/releases/tag/v1.0.2
> 
> That is better, in that it no longer crashes. But the first note distorts badly and subsequent notes don't play at all.
> 
> I'm using stock laptop sound card, ALSA drivers, and I've tried several combinations of priority and buffer sizes.
> 
> CPU is Pentium Silver N5030 with 8GB RAM.

How is CPU usage? I'm worried the Linux builds aren't being optimized

**Comment by garrettendi** [comment]
I'll have to run it with the System Monitor running. I'll get back to you.

**Comment by FigBug** [comment]
> I'll have to run it with the System Monitor running. I'll get back to you.

Fixed another bug, can you try this build: https://github.com/FigBug/Piano/actions/runs/20669919897

**Comment by garrettendi** [comment]
Same bug, see the bottom bar in the Reaper plugin:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0ab1276a-c687-4cd4-a0f2-d6751772bc5b" />

When I use another piano plugin (Boz Master Keys using wine/yabridge) those numbers are much more sensible.

**Comment by garrettendi** [comment]
I just tried the latest version and I'm still getting a lot of distortion and recording and playback are very slow and stuttering. I think it might actually be my CPU. It's a Pentium Silver N5030.

**Comment by garrettendi** [comment]
In the latest version, this seems to be fixed!
